#ifndef GSH_TRANS_WIGNER_GUARD_H
#define GSH_TRANS_WIGNER_GUARD_H

/**
 * @file Wigner.h
 * @brief The generalised Legendre functions, tabulated over colatitude.
 *
 * @details The value stored at upper index @f$N@f$, degree @f$l@f$ and order
 * @f$m@f$ is
 *
 * @f[ \sqrt{\frac{2l+1}{4\pi}}\, d^l_{Nm}(\theta), @f]
 *
 * where @f$d^l_{Nm} = P^N_{lm}(\cos\theta)@f$ is the generalised Legendre
 * function of Dahlen & Tromp (1998) eq. (C.115) — **upper index first**.
 * Orthonormalisation is the only normalisation offered.
 *
 * Values come from a two-term recursion up the degrees at fixed
 * @f$(N, \theta)@f$, seeded at @f$l = |N|@f$ and closed at each degree by the
 * two boundary orders @f$m = \pm l@f$. Nothing forms a factorial: the seed row
 * is generated by the binomial step @f$C(2l, k) = C(2l, k-1)(2l-k+1)/k@f$ and
 * the boundary values ride up the degree loop by their own one-term
 * recursion, which is both cheaper and more accurate than the closed form —
 * that exponentiates a logarithm of size @f$O(l\log 4)@f$ and loses bits in
 * proportion, where each recursion step multiplies by a factor of order one.
 *
 * The table is large: about 648 MB at @f$l_{\max} = 256@f$ with
 * @f$n_{\max} = 2@f$ over all upper indices, against 2.1 MB for a complex
 * field on the same grid. A grid may therefore decline to hold one and
 * generate each block as it is needed, which is what ComputeBlock is separable
 * for.
 *
 * @see WignerMatrices.h, which holds the same values in the layout a matrix
 * product wants, and is checked against this one.
 * @see docs/canonical-components.tex for the conventions.
 */

#include <omp.h>

#include <algorithm>
#include <cassert>
#include <cmath>
#include <concepts>
#include <cstddef>
#include <limits>
#include <numbers>
#include <ranges>
#include <span>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

#include "Concepts.h"
#include "Indexing.h"
#include "Utility.h"
#include "Views.h"

namespace GSHTrans {

/**
 * @brief The precision the Wigner recursion is *run* in, for values stored in
 * @p Real: at least double.
 *
 * @details Single precision is worth having for what is stored and moved --
 * half the table's traffic, half a field's memory -- and buys nothing in a
 * recursion that runs once, where it costs a great deal: the recursion's
 * range is the range of its arithmetic, and in single precision that ends
 * near degree 240. So a single-precision table is the double-precision one,
 * rounded. Double and long double are recursed in themselves, and nothing
 * about them changes.
 */
template <RealFloatingPoint Real>
using WignerRecursionReal =
    std::conditional_t<(std::numeric_limits<Real>::digits <
                        std::numeric_limits<double>::digits),
                       double, Real>;

/**
 * @brief The largest degree at which a table of Wigner functions is right.
 *
 * @details The recursion in degree is seeded at @f$l = |m|@f$ with a value of
 * about @f$(\sin\theta)^m@f$, and the column it starts grows back to order one
 * only once @f$l \sin\theta@f$ reaches @f$m@f$. A seed that has underflowed
 * *and* still matters therefore needs
 * @f$l_{\max}\, s|\ln s| > |\ln \mathrm{min}|@f$ for some
 * @f$s = \sin\theta@f$, and @f$s|\ln s|@f$ is largest at @f$s = 1/e@f$: the
 * plain recursion is safe if and only if
 * @f$l_{\max} < e\,|\ln \mathrm{min}|@f$. Measured, that puts the onset
 * within a per cent -- 1926 in double, where the table is right at 1900 and
 * wrong in the ninth place at 1930, and by order one at 3000.
 *
 * What is returned is a little less,
 * @f$\lfloor e\,(|\ln \mathrm{min}| - |\ln \epsilon|) \rfloor@f$, which
 * keeps the seed above @f$\mathrm{min}/\epsilon@f$ and so out of the denormal
 * range, where it loses bits before it loses everything: 1827 in double and
 * 30747 in long double. Single precision is recursed in double (see
 * WignerRecursionReal) and so shares double's limit and not the 194 its own
 * arithmetic would give.
 *
 * Above this a table is refused. The cure, an exponent carried beside each
 * column (Fukushima, J. Geod. 86, 2012), is known and not built: nothing
 * this library is used for comes near the limit.
 */
template <RealFloatingPoint Real>
constexpr std::ptrdiff_t MaxSafeDegree() {
  using Work = WignerRecursionReal<Real>;
  // |ln min| - |ln eps| in units of ln 2, exactly, from the format:
  // min = 2^(min_exponent - 1) and eps = 2^(1 - digits).
  constexpr auto bits = 2 - std::numeric_limits<Work>::min_exponent -
                        std::numeric_limits<Work>::digits;
  return static_cast<std::ptrdiff_t>(std::numbers::e_v<long double> *
                                     std::numbers::ln2_v<long double> *
                                     static_cast<long double>(bits));
}

namespace WignerDetails {

template <RealFloatingPoint Real>
class Arguments {
 public:
  Arguments() = default;

  constexpr Arguments(Real theta) {
    constexpr auto half = static_cast<Real>(1) / static_cast<Real>(2);
    sinHalf_ = std::sin(half * theta);
    cosHalf_ = std::cos(half * theta);
    atLeft_ = sinHalf_ < std::numeric_limits<Real>::min();
    atRight_ = cosHalf_ < std::numeric_limits<Real>::min();
    logSinHalf_ = atLeft_ ? static_cast<Real>(0) : std::log(sinHalf_);
    logCosHalf_ = atRight_ ? static_cast<Real>(0) : std::log(cosHalf_);
  }

  constexpr auto AtLeft() const { return atLeft_; }
  constexpr auto AtRight() const { return atRight_; }

  constexpr auto LogSinHalf() const { return logSinHalf_; }
  constexpr auto LogCosHalf() const { return logCosHalf_; }

  // The linear values are kept as well as their logarithms. The closed forms
  // below, and the seed row at a large upper index, need the logarithms,
  // because they form sqrt((2l)!/...) which is of order 4^l; the recursions
  // need the values themselves, and they stay
  // bounded because each step multiplies by about 2 sin(theta/2) cos(theta/2),
  // which is sin(theta).
  constexpr auto SinHalf() const { return sinHalf_; }
  constexpr auto CosHalf() const { return cosHalf_; }

 private:
  Real sinHalf_;
  Real cosHalf_;
  Real logSinHalf_;
  Real logCosHalf_;
  bool atLeft_;
  bool atRight_;
};

template <std::integral Int, RealFloatingPoint Real>
constexpr auto WignerMinOrder(Int l, Int n, const Arguments<Real> &arg) {
  // Check the inputs.
  assert(l >= 0);
  assert(std::abs(n) <= l);

  // Deal with l == 0 case
  if (l == 0) return static_cast<Real>(1);

  // Deal with special case at the left boundary.
  if (arg.AtLeft()) {
    return n == -l ? static_cast<Real>(1) : static_cast<Real>(0);
  }

  // Deal with special case at the right boundary.
  if (arg.AtRight()) {
    return n == l ? static_cast<Real>(1) : static_cast<Real>(0);
  }

  // Deal with the general case.
  constexpr auto half = static_cast<Real>(1) / static_cast<Real>(2);
  auto Fl = static_cast<Real>(l);
  auto Fn = static_cast<Real>(n);
  using std::exp;
  using std::lgamma;
  return exp(
      half * (lgamma(2 * Fl + 1) - lgamma(Fl - Fn + 1) - lgamma(Fl + Fn + 1)) +
      (Fl + Fn) * arg.LogSinHalf() + (Fl - Fn) * arg.LogCosHalf());
}

template <std::integral Int, RealFloatingPoint Real>
constexpr auto WignerMaxOrder(Int l, Int n, const Arguments<Real> &arg) {
  return MinusOneToPower(n + l) * WignerMinOrder(l, -n, arg);
}

template <std::integral Int, RealFloatingPoint Real>
constexpr auto WignerMinUpperIndex(Int l, Int m, const Arguments<Real> &arg) {
  return WignerMaxOrder(l, -m, arg);
}

template <std::integral Int, RealFloatingPoint Real>
constexpr auto WignerMaxUpperIndex(Int l, Int m, const Arguments<Real> &arg) {
  return WignerMinOrder(l, -m, arg);
}

// x^k for a small non-negative k. Written out because the exponents here are
// 2|n| and its neighbours -- four, for a rank-2 application -- and a loop of
// that length is both exact and cheaper than a call to pow.
template <RealFloatingPoint Real>
constexpr auto IntegerPower(Real x, std::ptrdiff_t k) {
  auto result = static_cast<Real>(1);
  for (auto i = std::ptrdiff_t{0}; i < k; i++) result *= x;
  return result;
}

// The two boundary values of a degree, run up the degrees rather than
// evaluated in closed form at each one.
//
// Compute needs d^l_{n,-l} and d^l_{n,l} once per degree, and the closed forms
// above cost three lgamma and an exp apiece. Paid once inside grid
// construction that is affordable; paid inside a transform, which is what a
// generating Wigner supplier does, it is of order 131k
// transcendental evaluations per upper index per transform at lMax = 256,
// comparable to the whole transform.
//
// The boundary obeys a one-term recursion in l. Writing
//
//   WignerMinOrder(l, n) = sqrt((2l)! / ((l-n)! (l+n)!)) s^{l+n} c^{l-n}
//
// with s = sin(theta/2) and c = cos(theta/2), the ratio at fixed n is
//
//   d(l) / d(l-1) = sqrt( 2l(2l-1) / ((l-n)(l+n)) ) * s * c,
//
// which is valid only for l > |n|: at l = |n| one factor of the denominator
// vanishes and the seed is needed, where the square root is one and the value
// is s^{2|n|} at n = +|n| and c^{2|n|} at n = -|n|. So one short power per
// (n, theta) replaces three lgamma and an exp per (l, theta).
//
// Both boundaries ride on the same recursion, because the ratio depends on n
// only through n^2 and because
//
//   WignerMaxOrder(l, n) = (-1)^{n+l} WignerMinOrder(l, -n),
//
// so carrying WignerMinOrder(l, +-n) as two running values gives both.
//
// This is more robust than the closed form rather than less. The closed form
// works in logarithms because sqrt((2l)!/...) is of order 4^l and overflows
// long before the value it belongs to, which is bounded by one; each step of
// the recursion multiplies by about 2 s c = sin(theta), so nothing large is
// ever formed. The special values at theta = 0 and pi come out of the seeds
// unaided: the ratio is 0 * infinity there, but the seed is already the exact
// 0 or 1 that the closed form's AtLeft and AtRight branches return, and the
// factor is zero thereafter.
//
// Values are unnormalised. Compute applies sqrt((2l+1)/4pi) to the whole block
// afterwards, which is also the contract a generating supplier must meet.
template <RealFloatingPoint Real>
class BoundaryValues {
 public:
  using Int = std::ptrdiff_t;  ///< Signed index type used throughout.

  constexpr BoundaryValues(Int n, const Arguments<Real> &arg)
      : n_{n},
        l_{n < 0 ? -n : n},
        sinCos_{arg.SinHalf() * arg.CosHalf()},
        atUpperIndex_{IntegerPower(n >= 0 ? arg.SinHalf() : arg.CosHalf(),
                                   2 * (n < 0 ? -n : n))},
        atMinusUpperIndex_{IntegerPower(n >= 0 ? arg.CosHalf() : arg.SinHalf(),
                                        2 * (n < 0 ? -n : n))} {}

  // Move to the next degree. Degrees must be visited in ascending order from
  // |n|, which is what Compute's loops already do; the recursion carries no
  // way to skip one or to go back.
  constexpr void Advance() {
    l_++;
    const auto Fl = static_cast<Real>(l_);
    const auto Fn = static_cast<Real>(n_);
    const auto factor =
        std::sqrt(2 * Fl * (2 * Fl - 1) / ((Fl - Fn) * (Fl + Fn))) * sinCos_;
    atUpperIndex_ *= factor;
    atMinusUpperIndex_ *= factor;
  }

  constexpr auto Degree() const { return l_; }

  // d^l_{n,-l}, which is WignerMinOrder(l, n).
  constexpr auto MinOrder() const { return atUpperIndex_; }

  // d^l_{n,l}, which is WignerMaxOrder(l, n).
  constexpr auto MaxOrder() const {
    return MinusOneToPower<Real>(n_ + l_) * atMinusUpperIndex_;
  }

 private:
  Int n_;
  Int l_;
  Real sinCos_;
  Real atUpperIndex_;
  Real atMinusUpperIndex_;
};

// The square-root tables the recursion indexes: sqrt(k) and its reciprocal,
// for k up to lMax + max(mMax, |n|).
//
// Lifted out of Wigner::PreCompute for the same reason as ComputeBlock: a
// generating grid needs them without needing a table, and two definitions of
// the same tables would be one too many. They are the tiny tables that replace
// the large one -- 2 lMax + 1 entries each.
template <RealFloatingPoint Real>
auto PreComputeTables(std::ptrdiff_t lMax, std::ptrdiff_t mMax,
                      std::ptrdiff_t nMax) {
  using Int = std::ptrdiff_t;
  // |nMax| and not nMax: a table holding one upper index may hold a negative
  // one, and the recursion indexes at l - n as well as at l + n.
  const auto size = lMax + std::max(mMax, nMax < 0 ? -nMax : nMax) + 1;
  auto sqrtInt = std::vector<Real>();
  auto sqrtIntInv = std::vector<Real>();
  sqrtInt.reserve(size);
  sqrtIntInv.reserve(size);
  std::generate_n(std::back_inserter(sqrtInt), size, [m = Int{0}]() mutable {
    return std::sqrt(static_cast<Real>(m++));
  });
  std::transform(sqrtInt.begin(), sqrtInt.end(), std::back_inserter(sqrtIntInv),
                 [](auto x) { return x > 0 ? 1 / x : 0; });
  return std::pair(std::move(sqrtInt), std::move(sqrtIntInv));
}

// The recursion itself, as a pure function of a destination view, an upper
// index, a colatitude and the two square-root tables.
//
// Lifted out of Wigner::Compute unchanged, so that the values can be written
// somewhere other than a stored table -- into per-thread scratch inside a
// transform, which is what a generating grid does. Wigner::Compute is the
// wrapper that points the view at its own storage.
// The destination's degree and order bounds come from the view, so a caller
// wanting only the degrees up to some truncation asks for a view of that
// extent and pays for no more.
template <RealFloatingPoint Real, OrderIndexRange MRange>
constexpr void ComputeBlock(GSHView<Real, MRange> d, std::ptrdiff_t n,
                            Real theta, std::span<const Real> sqrtInt,
                            std::span<const Real> sqrtIntInv) {
  using Int = std::ptrdiff_t;

  // The extent to fill comes from the view rather than from any table, which
  // is what lets a caller ask for the degrees up to a truncation and pay for
  // no more.
  const auto lMax = d.MaxDegree();
  const auto mBound = d.MaxOrder();

  auto arg = Arguments(theta);
  const auto cos = std::cos(theta);
  const auto nAbs = std::abs(n);

  // Set the values for l == |n|
  //
  // This is the seed row, and at l = |n| the closed form reduces to
  //
  //   WignerMinOrder(l, -m) = sqrt(C(2l, l+m)) s^{l-m} c^{l+m},
  //
  // whose binomial row is generated exactly by the standard step
  // C(2l, k) = C(2l, k-1) (2l - k + 1) / k. The row is at most 2|n| + 1
  // long -- five entries for a rank-2 application -- so unlike the boundary
  // recursion this is not about cost.
  //
  // It is about lgamma. glibc's writes the global signgam, and ComputeAll
  // calls Compute from every thread, so the closed form is a data race here
  // -- benign, since nothing reads signgam, but the only genuine one
  // ThreadSanitizer finds in this library. The values are also exact this
  // way, where the closed form is merely accurate.
  {
    const auto l = nAbs;
    const auto s = arg.SinHalf();
    const auto c = arg.CosHalf();
    auto m = d[l].MinOrder();
    auto iter = d[l].begin();
    auto finish = d[l].end();

    // The binomial itself is formed only while it fits. C(2l, l) is about
    // 4^l, so past l = max_exponent / 2 it overflows before its root is taken
    // -- |n| above 508 in double -- and the row, and everything recursed from
    // it, came back non-finite. Beyond that the entry is formed from
    // logarithms instead: the binomial's as a running sum, which needs no
    // lgamma, and the two that Arguments already carries. That is accurate
    // and not exact, which is why it is not simply used throughout: every
    // table anyone has built sits below the switch, and stays bit for bit
    // what it was.
    constexpr auto directLimit =
        static_cast<Int>((std::numeric_limits<Real>::max_exponent - 8) / 2);

    if (l <= directLimit) {
      // C(2l, l+m) at the first order stored, formed by the same step.
      auto binomial = static_cast<Real>(1);
      for (auto k = Int{1}; k <= l + m; k++) {
        binomial *= static_cast<Real>(2 * l - k + 1) / static_cast<Real>(k);
      }

      while (iter != finish) {
        const auto root = std::sqrt(binomial);
        *iter++ = n >= 0
                      ? root * IntegerPower(s, l - m) * IntegerPower(c, l + m)
                      : MinusOneToPower<Real>(l - m) * root *
                            IntegerPower(s, l + m) * IntegerPower(c, l - m);
        binomial *= static_cast<Real>(l - m) / static_cast<Real>(l + m + 1);
        m++;
      }
    } else {
      auto logBinomial = static_cast<Real>(0);
      for (auto k = Int{1}; k <= l + m; k++) {
        logBinomial +=
            std::log(static_cast<Real>(2 * l - k + 1) / static_cast<Real>(k));
      }

      // ln(x^k) from ln x. At a pole one of the two half-angle functions is
      // zero, and Arguments does not store its logarithm as minus infinity:
      // it stores zero and raises a flag. So the flag is asked, and a positive
      // power of a vanishing base is sent to minus infinity here, whose
      // exponential is the zero it should be. The power zero is one whatever
      // the base.
      constexpr auto minusInfinity = -std::numeric_limits<Real>::infinity();
      const auto power = [](Real logX, bool vanishes, Int k) {
        if (k == 0) return static_cast<Real>(0);
        return vanishes ? minusInfinity : static_cast<Real>(k) * logX;
      };

      while (iter != finish) {
        const auto sPower = n >= 0 ? l - m : l + m;
        const auto cPower = n >= 0 ? l + m : l - m;
        const auto value = std::exp(
            logBinomial / 2 + power(arg.LogSinHalf(), arg.AtLeft(), sPower) +
            power(arg.LogCosHalf(), arg.AtRight(), cPower));
        *iter++ = n >= 0 ? value : MinusOneToPower<Real>(l - m) * value;
        if (m < l) {
          logBinomial +=
              std::log(static_cast<Real>(l - m) / static_cast<Real>(l + m + 1));
        }
        m++;
      }
    }
  }

  // The boundary terms of every higher degree, on the one-term recursion
  // that replaces the closed form at m = +-l.
  auto boundary = BoundaryValues<Real>(n, arg);

  // Set the values for l == n+1 if needed.
  if (nAbs < lMax) {
    const auto l = nAbs + 1;
    const auto mMin = d[l].MinOrder();
    const auto mMax = d[l].MaxOrder();
    auto m = mMin;

    // The boundary values are read only while the degree is still growing:
    // every use below is guarded by l <= mMax, and that degree's mMax is
    // min(l, mBound). Once l passes mBound they are never wanted again, so
    // the recursion stops rather than being advanced unused.
    if (l <= mBound) boundary.Advance();

    // Set iterators
    auto iterMinusOne = d[l - 1].begin();
    auto finishMinusOne = d[l - 1].end();
    auto iter = d[l].begin();

    // Add in value at m == -l if needed.
    if constexpr (std::same_as<MRange, All>) {
      if (l <= mMax) {
        *iter++ = boundary.MinOrder();
        m++;
      }
    }

    // Add in interior orders using one-term recursion.
    {
      const auto alpha = (2 * l - 1) * l * cos * sqrtIntInv[l + nAbs];
      const auto beta = (n < 0 ? -1 : 1) * (2 * l - 1) * sqrtIntInv[l + nAbs];

      while (iterMinusOne != finishMinusOne) {
        const auto f1 =
            (alpha - beta * m) * sqrtIntInv[l - m] * sqrtIntInv[l + m];
        *iter++ = f1 * *iterMinusOne++;
        m++;
      }
    }

    // Add in value at m == l if needed
    if (l <= mMax) {
      *iter++ = boundary.MaxOrder();
    }
  }

  // Do the remaining degrees
  for (auto l = nAbs + 2; l <= lMax; l++) {
    const auto mMin = d[l].MinOrder();
    const auto mMax = d[l].MaxOrder();
    auto m = mMin;

    if (l <= mBound) boundary.Advance();

    // Set iterators.
    auto iterMinusTwo = d[l - 2].begin();
    auto finishMinusTwo = d[l - 2].end();
    auto iterMinusOne = d[l - 1].begin();
    auto iter = d[l].begin();

    // Add in lower boundary terms if still growing.
    if constexpr (std::same_as<MRange, All>) {
      if (l <= mMax) {
        {
          // Add in the m == -l term.
          *iter++ = boundary.MinOrder();
          m++;
        }
        {
          // Now do the m == -l+1 term using one-point recursion.
          const auto f1 = (2 * l - 1) * (l * (l - 1) * cos - m * n) *
                          sqrtIntInv[l - n] * sqrtIntInv[l + n] *
                          sqrtIntInv[l - m] * sqrtIntInv[l + m] /
                          static_cast<Real>(l - 1);
          *iter++ = f1 * (*iterMinusOne++);
          m++;
        }
      }

      // Add in the lower boundary term at the critical degree.
      if (l == mMax + 1) {
        const auto f1 = (2 * l - 1) * (l * (l - 1) * cos - m * n) *
                        sqrtIntInv[l - n] * sqrtIntInv[l + n] *
                        sqrtIntInv[l - m] * sqrtIntInv[l + m] /
                        static_cast<Real>(l - 1);
        *iter++ = f1 * (*iterMinusOne++);
        m++;
      }
    }

    // Apply two-term recusion for the interior orders.
    {
      const auto alpha =
          (2 * l - 1) * l * cos * sqrtIntInv[l - n] * sqrtIntInv[l + n];
      const auto beta = (2 * l - 1) * n * sqrtIntInv[l - n] *
                        sqrtIntInv[l + n] / static_cast<Real>(l - 1);
      const auto gamma = l * sqrtInt[l - 1 - n] * sqrtInt[l - 1 + n] *
                         sqrtIntInv[l - n] * sqrtIntInv[l + n] /
                         static_cast<Real>(l - 1);

      while (iterMinusTwo != finishMinusTwo) {
        const auto denom = sqrtIntInv[l - m] * sqrtIntInv[l + m];
        const auto f1 = (alpha - beta * m) * denom;
        const auto f2 = gamma * sqrtInt[l - 1 - m] * sqrtInt[l - 1 + m] * denom;
        *iter++ = f1 * *iterMinusOne++ - f2 * *iterMinusTwo++;
        m++;
      }
    }

    // Add in the upper boundary terms if still growing.
    if (l <= mMax) {
      // Add in m == l - 1 term using one-point recursion.
      {
        const auto f1 = (2 * l - 1) * (l * (l - 1) * cos - m * n) *
                        sqrtIntInv[l - n] * sqrtIntInv[l + n] *
                        sqrtIntInv[l - m] * sqrtIntInv[l + m] /
                        static_cast<Real>(l - 1);
        *iter++ = f1 * (*iterMinusOne++);
        m++;
      }
      // Now do m == l.
      *iter++ = boundary.MaxOrder();
    }

    // Add in the upper boundary term at the critical degree.
    if (l == mMax + 1) {
      // Update the iterators.

      const auto f1 = (2 * l - 1) * (l * (l - 1) * cos - m * n) *
                      sqrtIntInv[l - n] * sqrtIntInv[l + n] *
                      sqrtIntInv[l - m] * sqrtIntInv[l + m] /
                      static_cast<Real>(l - 1);
      *iter++ = f1 * (*iterMinusOne++);
    }
  }

  // Orthonormalise: the stored value at (l, m) becomes
  // sqrt((2l+1)/(4 pi)) d^l_{nm}. This is the only normalisation the
  // library offers.
  {
    const auto factor = std::numbers::inv_sqrtpi_v<Real> / static_cast<Real>(2);
    for (auto l : d.Degrees()) {
      auto start = d[l].begin();
      auto finish = d[l].end();
      std::transform(start, finish, start, [l, factor](auto p) {
        return factor * std::sqrt(static_cast<Real>(2 * l + 1)) * p;
      });
    }
  }
}

// Refuse a degree the recursion cannot reach. One function, so that the three
// things that build tables -- Wigner, WignerMatrices and a generating grid,
// which has no table to do the refusing -- say the same thing.
template <RealFloatingPoint Real>
void CheckSafeDegree(std::ptrdiff_t lMax) {
  if (lMax > MaxSafeDegree<Real>()) {
    throw std::invalid_argument(
        "The Wigner recursion underflows above degree " +
        std::to_string(MaxSafeDegree<Real>()) +
        " in this precision, and the table it would build is silently wrong "
        "by order one, so lMax = " +
        std::to_string(lMax) +
        " is refused. See MaxSafeDegree for where the limit comes from");
  }
}

// The square-root tables, in the precision the recursion runs in.
template <RealFloatingPoint Real>
auto PreComputeRecursionTables(std::ptrdiff_t lMax, std::ptrdiff_t mMax,
                               std::ptrdiff_t nMax) {
  return PreComputeTables<WignerRecursionReal<Real>>(lMax, mMax, nMax);
}

// Fill a block stored in Real, recursing in WignerRecursionReal<Real>.
//
// For double and long double the two are one type and this *is*
// ComputeBlock, called on the destination: not a value changes. For single
// precision the recursion runs into this thread's scratch in double and is
// narrowed into the destination, which is laid out identically, so the
// narrowing is one pass over a contiguous block.
//
// Every route to a single-precision value comes through here or does the same
// thing -- WignerMatrices narrows as it scatters -- and that is a requirement
// and not a convenience: a stored grid and a generating one agree bit for
// bit, which they can only do if both round the same double.
template <RealFloatingPoint Real, OrderIndexRange MRange>
void FillBlock(GSHView<Real, MRange> d, std::ptrdiff_t n,
               WignerRecursionReal<Real> theta,
               std::span<const WignerRecursionReal<Real>> sqrtInt,
               std::span<const WignerRecursionReal<Real>> sqrtIntInv) {
  using Work = WignerRecursionReal<Real>;
  if constexpr (std::same_as<Work, Real>) {
    ComputeBlock(d, n, theta, sqrtInt, sqrtIntInv);
  } else {
    thread_local auto scratch = std::vector<Work>{};
    const auto size = static_cast<std::size_t>(d.Size());
    if (scratch.size() < size) scratch.resize(size);
    ComputeBlock(
        GSHView<Work, MRange>(d.MaxDegree(), d.MaxOrder(), n, scratch.data()),
        n, theta, sqrtInt, sqrtIntInv);
    std::transform(scratch.begin(),
                   scratch.begin() + static_cast<std::ptrdiff_t>(size),
                   d.begin(), [](Work x) { return static_cast<Real>(x); });
  }
}

}  // namespace WignerDetails

/**
 * @brief A table of generalised Legendre functions over a set of colatitudes.
 *
 * @tparam Real_ The precision.
 * @tparam MRange_ Whether each block holds all orders or only the
 * non-negative ones.
 * @tparam NRange_ Which upper indices the table covers.
 * @tparam AngleRange_ Whether the table holds one colatitude or many.
 */
template <RealFloatingPoint Real_, OrderIndexRange MRange_ = All,
          IndexRange NRange_ = Single, AngleIndexRange AngleRange_ = Single>
class Wigner {
 public:
  using Int = std::ptrdiff_t;  ///< Signed index type used throughout.
  using Real = Real_;          ///< The precision.
  /// The precision the recursion runs in: at least double.
  using Work = WignerRecursionReal<Real>;
  /// Whether all orders are stored, or only the non-negative ones.
  using MRange = MRange_;
  using NRange = NRange_;          ///< Which upper indices are covered.
  using AngleRange = AngleRange_;  ///< Whether one colatitude is held, or many.

  /** @brief An empty table. */
  Wigner() = default;

  /**
   * @brief Builds the table over a set of colatitudes.
   * @param lMax The largest degree.
   * @param mMax The largest order; blocks stop widening beyond it.
   * @param nMax The largest upper index.
   * @param theta The colatitudes, in @f$[0, \pi]@f$.
   * @throws std::invalid_argument if the degree or the largest order is
   * negative, if the upper index exceeds the degree or is negative in a table
   * holding more than one, or if a colatitude lies outside @f$[0, \pi]@f$.
   */
  template <std::ranges::random_access_range Range>
  requires std::ranges::sized_range<Range> &&
               RealFloatingPoint<std::ranges::range_value_t<Range>>
  Wigner(Int lMax, Int mMax, Int nMax, Range &&theta)
      : lMax_{Checked(lMax, mMax, nMax)},
        mMax_{mMax},
        nMax_{nMax},
        nTheta_(static_cast<Int>(std::ranges::size(theta))) {
    // Compute the offsets and allocate memory.
    {
      offset_.reserve(NumberOfUpperIndices() * NumberOfAngles());
      auto size = std::size_t{0};
      for (auto [n, iTheta] : Indices()) {
        offset_.push_back(size);
        size += GSHIndices<MRange>(MaxDegree(), mMax_, n).Size();
      }
      data_ = std::vector<Real>(size);
    }
    ComputeAll(theta);
  }

  /** @brief Builds the table over one colatitude. */
  Wigner(Int lMax, Int mMax, Int nMax, Real theta)
  requires std::same_as<AngleRange, Single>
      : Wigner(lMax, mMax, nMax, std::vector{theta}) {}

  /** @brief Copy constructor. */
  Wigner(const Wigner &) = default;
  /** @brief Move constructor. */
  Wigner(Wigner &&) = default;
  /** @brief Copy assignment. */
  Wigner &operator=(const Wigner &) = default;
  /** @brief Move assignment. */
  Wigner &operator=(Wigner &&) = default;

  /**
   * @brief Recomputes the table at new colatitudes, reusing its storage.
   * @param theta The new colatitudes; there must be as many as before.
   */
  template <std::ranges::random_access_range Range>
  requires std::ranges::sized_range<Range> &&
           RealFloatingPoint<std::ranges::range_value_t<Range>>
  void ReCompute(Range &&theta) {
    if (static_cast<Int>(std::ranges::size(theta)) != nTheta_) {
      throw std::invalid_argument(
          "A Wigner table is recomputed in the storage it has, so at as many "
          "colatitudes as it was built with: " +
          std::to_string(nTheta_) + ", and not " +
          std::to_string(std::ranges::size(theta)));
    }
    ComputeAll(theta);
  }

  /** @brief Recomputes the table at a new colatitude. */
  void ReCompute(Real theta)
  requires std::same_as<AngleRange, Single>
  {
    ComputeAll(std::vector{theta});
  }

  /** @brief The smallest degree stored at upper index @p n, namely @f$|n|@f$.
   */
  auto MinDegree(Int n) const {
    assert(std::abs(n) <= nMax_);
    return std::abs(n);
  }
  /** @brief The smallest degree stored. */
  auto MinDegree() const
  requires std::same_as<NRange, Single>
  {
    return std::abs(nMax_);
  }
  /** @brief The largest degree stored. */
  auto MaxDegree() const { return lMax_; }

  /** @brief Every degree stored. */
  auto Degrees() const
  requires std::same_as<NRange, Single>
  {
    return std::ranges::views::iota(MinDegree(), MaxDegree() + 1);
  }

  /** @brief Every degree stored at upper index @p n. */
  auto Degrees(Int n) const {
    return std::ranges::views::iota(MinDegree(n), MaxDegree() + 1);
  }

  /** @brief The smallest order stored at degree @p l. */
  auto MinOrder(Int l) const {
    assert(l >= 0 && l <= MaxDegree());
    if constexpr (std::same_as<MRange, All>) {
      return -std::min(l, mMax_);
    } else {
      return 0;
    }
  }
  /** @brief The largest order stored anywhere in the table. */
  auto MaxOrder() const { return mMax_; }
  /** @brief The largest order stored at degree @p l. */
  auto MaxOrder(Int l) const { return std::min(l, mMax_); }

  /** @brief Every order stored at degree @p l. */
  auto Orders(Int l) const {
    return std::ranges::views::iota(MinOrder(l), MaxOrder(l) + 1);
  }

  // Return upper index information.
  /** @brief The smallest upper index stored. */
  auto MinUpperIndex() const {
    if constexpr (std::same_as<NRange_, All>) {
      return -nMax_;
    } else if constexpr (std::same_as<NRange_, NonNegative>) {
      return Int{0};
    } else {
      return nMax_;
    }
  }

  /** @brief The largest upper index stored. */
  auto MaxUpperIndex() const { return nMax_; }

  /** @brief Every upper index stored. */
  auto UpperIndices() const {
    return std::ranges::views::iota(MinUpperIndex(), MaxUpperIndex() + 1);
  }

  /** @brief How many upper indices are stored. */
  auto NumberOfUpperIndices() const {
    return MaxUpperIndex() - MinUpperIndex() + 1;
  }

  // Return angle information.
  /** @brief How many colatitudes are stored. */
  auto NumberOfAngles() const { return nTheta_; }

  /** @brief Indices of the stored colatitudes. */
  auto AngleIndices() const {
    return std::ranges::views::iota(Int{0}, nTheta_);
  }

  /**
   * @brief Every @f$(n, i_\theta)@f$ pair, in storage order.
   * @details Upper index outermost, colatitude fastest, which is how the
   * blocks are laid out.
   */
  auto Indices() const {
    return std::ranges::views::cartesian_product(UpperIndices(),
                                                 AngleIndices());
  }

  /** @brief The block of values for upper index @p n at colatitude @p iTheta.
   */
  auto operator[](Int n, Int iTheta) const {
    return ConstGSHView<Real, MRange>(MaxDegree(), MaxOrder(), n,
                                      &data_[Offset(n, iTheta)]);
  }

  /** @brief The block for upper index @p n, when only one colatitude is held.
   */
  auto operator[](Int n) const
  requires std::same_as<AngleRange, Single> && (!std::same_as<NRange, Single>)
  {
    return operator[](n, 0);
  }

  /** @brief The block at colatitude @p iTheta, when only one upper index is
   * held. */
  auto operator[](Int iTheta) const
  requires std::same_as<NRange, Single> && (!std::same_as<AngleRange, Single>)
  {
    return operator[](nMax_, iTheta);
  }

  /** @brief The row of orders at degree @p l, when one block is held. */
  auto operator[](Int l) const
  requires std::same_as<NRange, Single> && std::same_as<AngleRange, Single>
  {
    return operator[](nMax_, 0)[l];
  }

 private:
  // Zero, so that a default-constructed table is an empty one and not one
  // whose shape is whatever was in memory.
  Int lMax_{};    // Maximum degree.
  Int mMax_{};    // Maximum order.
  Int nMax_{};    // Maximum upper index.
  Int nTheta_{};  // Number of colatitudes.

  // The shape, checked before anything is sized by it. This is a public class
  // and these are a caller's numbers; left to the index classes' asserts they
  // were unchecked in a Release build, where an upper index above the degree
  // made a block's size negative and the table was written through anyway.
  static Int Checked(Int lMax, Int mMax, Int nMax) {
    if (lMax < 0) {
      throw std::invalid_argument(
          "A Wigner table's maximum degree must be at least zero");
    }
    WignerDetails::CheckSafeDegree<Real>(lMax);
    if (mMax < 0) {
      throw std::invalid_argument(
          "A Wigner table's maximum order must be at least zero");
    }
    if (nMax > lMax || -nMax > lMax) {
      throw std::invalid_argument(
          "A Wigner table's upper index cannot exceed its maximum degree, "
          "since d^l_{nm} needs l >= |n|");
    }
    if constexpr (not std::same_as<NRange, Single>) {
      if (nMax < 0) {
        throw std::invalid_argument(
            "A Wigner table over a range of upper indices is given the "
            "largest of them, which cannot be negative. One negative upper "
            "index is NRange = Single");
      }
    }
    return lMax;
  }

  // Vector storing the values.
  std::vector<Real> data_;

  // Vector storing data offsets.
  std::vector<std::size_t> offset_;

  // Offset for values for (n, iTheta).
  auto Offset(Int n, Int iTheta) const {
    return offset_[NumberOfAngles() * (n - MinUpperIndex()) + iTheta];
  }

  template <std::ranges::random_access_range Range>
  requires std::ranges::sized_range<Range> &&
           RealFloatingPoint<std::ranges::range_value_t<Range>>
  void ComputeAll(Range &&thetaRange) {
    // Here, and so for ReCompute as well as construction. Written to refuse a
    // NaN, which a pair of comparisons the other way round would admit.
    for (auto theta : thetaRange) {
      if (!(theta >= 0 && theta <= std::numbers::pi_v<Real>)) {
        throw std::invalid_argument("A colatitude must lie in [0, pi], and " +
                                    std::to_string(theta) + " does not");
      }
    }

    const auto [sqrtInt, sqrtIntInv] =
        WignerDetails::PreComputeRecursionTables<Real>(MaxDegree(), MaxOrder(),
                                                       MaxUpperIndex());
    const auto sqrtIntView = std::span<const Work>(sqrtInt);
    const auto sqrtIntInvView = std::span<const Work>(sqrtIntInv);

    // Flattened to an integer loop and decoded inside. OpenMP's canonical loop
    // form wants an integer induction variable or, from 5.0, a random-access
    // iterator loop; a structured binding over a cartesian_product view is
    // neither obviously conforming nor portable.
    //
    // The region is suppressed when one is already open, so that a caller
    // threading over grids or slices does not nest with this one. Exactly one
    // level threads.
    const auto nAngles = NumberOfAngles();
    const auto count = NumberOfUpperIndices() * nAngles;
    const auto minUpperIndex = MinUpperIndex();
    const bool nested = omp_in_parallel();

    // Nothing may leave a region: see ExceptionCapture.
    auto capture = Details::ExceptionCapture{};
#pragma omp parallel for schedule(static) if (!nested)
    for (Int index = 0; index < count; index++) {
      if (capture.Failed()) continue;
      capture.Run([&] {
        const auto n = minUpperIndex + index / nAngles;
        const auto iTheta = index % nAngles;
        Compute(n, iTheta, static_cast<Work>(thetaRange[iTheta]), sqrtIntView,
                sqrtIntInvView);
      });
    }
    capture.Rethrow();
  }

  // Point the recursion at this table's storage for one (n, iTheta).
  void Compute(Int n, Int iTheta, Work theta, std::span<const Work> sqrtInt,
               std::span<const Work> sqrtIntInv) {
    WignerDetails::FillBlock(
        GSHView<Real, MRange>(lMax_, mMax_, n, &data_[Offset(n, iTheta)]), n,
        theta, sqrtInt, sqrtIntInv);
  }
};
}  // namespace GSHTrans

#endif
