#ifndef GSH_TRANS_WIGNER_GUARD_H
#define GSH_TRANS_WIGNER_GUARD_H

/**
 * @file Wigner.h
 * @brief The generalised Legendre functions, tabulated over colatitude.
 *
 * @details The value stored at upper index @f$N@f$, degree @f$l@f$ and order
 * @f$m@f$ is
 *
 * @f[ \sqrt{\frac{2l+1}{4\pi}}\, d^l_{Nm}(\theta), @f]
 *
 * where @f$d^l_{Nm} = P^N_{lm}(\cos\theta)@f$ is the generalised Legendre
 * function of Dahlen & Tromp (1998) eq. (C.115) — **upper index first**.
 * Orthonormalisation is the only normalisation offered.
 *
 * Values come from a two-term recursion up the degrees at fixed
 * @f$(N, \theta)@f$, seeded at @f$l = |N|@f$ and closed at each degree by the
 * two boundary orders @f$m = \pm l@f$. Nothing forms a factorial: the seed row
 * is generated by the binomial step @f$C(2l, k) = C(2l, k-1)(2l-k+1)/k@f$ and
 * the boundary values ride up the degree loop by their own one-term
 * recursion, which is both cheaper and more accurate than the closed form —
 * that exponentiates a logarithm of size @f$O(l\log 4)@f$ and loses bits in
 * proportion, where each recursion step multiplies by a factor of order one.
 *
 * The table is large: about 648 MB at @f$l_{\max} = 256@f$ with
 * @f$n_{\max} = 2@f$ over all upper indices, against 2.1 MB for a complex
 * field on the same grid. A grid may therefore decline to hold one and
 * generate each block as it is needed, which is what ComputeBlock is separable
 * for.
 *
 * @see WignerMatrices.h, which holds the same values in the layout a matrix
 * product wants, and is checked against this one.
 * @see docs/canonical-components.tex for the conventions.
 */

#include <omp.h>

#include <algorithm>
#include <cassert>
#include <cmath>
#include <concepts>
#include <cstddef>
#include <limits>
#include <numbers>
#include <ranges>
#include <span>
#include <utility>
#include <vector>

#include "Concepts.h"
#include "Indexing.h"
#include "Utility.h"
#include "Views.h"

namespace GSHTrans {

namespace WignerDetails {

template <RealFloatingPoint Real>
class Arguments {
 public:
  Arguments() = default;

  constexpr Arguments(Real theta) {
    constexpr auto half = static_cast<Real>(1) / static_cast<Real>(2);
    _sinHalf = std::sin(half * theta);
    _cosHalf = std::cos(half * theta);
    _atLeft = _sinHalf < std::numeric_limits<Real>::min();
    _atRight = _cosHalf < std::numeric_limits<Real>::min();
    _logSinHalf = _atLeft ? static_cast<Real>(0) : std::log(_sinHalf);
    _logCosHalf = _atRight ? static_cast<Real>(0) : std::log(_cosHalf);
  }

  constexpr auto AtLeft() const { return _atLeft; }
  constexpr auto AtRight() const { return _atRight; }

  constexpr auto LogSinHalf() const { return _logSinHalf; }
  constexpr auto LogCosHalf() const { return _logCosHalf; }

  // The linear values are kept as well as their logarithms. The closed forms
  // below need the logarithms, because they form sqrt((2l)!/...) which is of
  // order 4^l; the recursions need the values themselves, and they stay
  // bounded because each step multiplies by about 2 sin(theta/2) cos(theta/2),
  // which is sin(theta).
  constexpr auto SinHalf() const { return _sinHalf; }
  constexpr auto CosHalf() const { return _cosHalf; }

 private:
  Real _sinHalf;
  Real _cosHalf;
  Real _logSinHalf;
  Real _logCosHalf;
  bool _atLeft;
  bool _atRight;
};

template <std::integral Int, RealFloatingPoint Real>
constexpr auto WignerMinOrder(Int l, Int n, const Arguments<Real> &arg) {
  // Check the inputs.
  assert(l >= 0);
  assert(std::abs(n) <= l);

  // Deal with l == 0 case
  if (l == 0) return static_cast<Real>(1);

  // Deal with special case at the left boundary.
  if (arg.AtLeft()) {
    return n == -l ? static_cast<Real>(1) : static_cast<Real>(0);
  }

  // Deal with special case at the right boundary.
  if (arg.AtRight()) {
    return n == l ? static_cast<Real>(1) : static_cast<Real>(0);
  }

  // Deal with the general case.
  constexpr auto half = static_cast<Real>(1) / static_cast<Real>(2);
  auto Fl = static_cast<Real>(l);
  auto Fn = static_cast<Real>(n);
  using std::exp;
  using std::lgamma;
  return exp(
      half * (lgamma(2 * Fl + 1) - lgamma(Fl - Fn + 1) - lgamma(Fl + Fn + 1)) +
      (Fl + Fn) * arg.LogSinHalf() + (Fl - Fn) * arg.LogCosHalf());
}

template <std::integral Int, RealFloatingPoint Real>
constexpr auto WignerMaxOrder(Int l, Int n, Arguments<Real> &arg) {
  return MinusOneToPower(n + l) * WignerMinOrder(l, -n, arg);
}

template <std::integral Int, RealFloatingPoint Real>
constexpr auto WignerMinUpperIndex(Int l, Int m, Arguments<Real> &arg) {
  return WignerMaxOrder(l, -m, arg);
}

template <std::integral Int, RealFloatingPoint Real>
constexpr auto WignerMaxUpperIndex(Int l, Int m, Arguments<Real> &arg) {
  return WignerMinOrder(l, -m, arg);
}

// x^k for a small non-negative k. Written out because the exponents here are
// 2|n| and its neighbours -- four, for a rank-2 application -- and a loop of
// that length is both exact and cheaper than a call to pow.
template <RealFloatingPoint Real>
constexpr auto IntegerPower(Real x, std::ptrdiff_t k) {
  auto result = static_cast<Real>(1);
  for (auto i = std::ptrdiff_t{0}; i < k; i++) result *= x;
  return result;
}

// The two boundary values of a degree, run up the degrees rather than
// evaluated in closed form at each one.
//
// Compute needs d^l_{n,-l} and d^l_{n,l} once per degree, and the closed forms
// above cost three lgamma and an exp apiece. Paid once inside grid
// construction that is affordable; paid inside a transform, which is what a
// generating Wigner supplier does (core-plan.md step F'), it is of order 131k
// transcendental evaluations per upper index per transform at lMax = 256,
// comparable to the whole transform.
//
// The boundary obeys a one-term recursion in l. Writing
//
//   WignerMinOrder(l, n) = sqrt((2l)! / ((l-n)! (l+n)!)) s^{l+n} c^{l-n}
//
// with s = sin(theta/2) and c = cos(theta/2), the ratio at fixed n is
//
//   d(l) / d(l-1) = sqrt( 2l(2l-1) / ((l-n)(l+n)) ) * s * c,
//
// which is valid only for l > |n|: at l = |n| one factor of the denominator
// vanishes and the seed is needed, where the square root is one and the value
// is s^{2|n|} at n = +|n| and c^{2|n|} at n = -|n|. So one short power per
// (n, theta) replaces three lgamma and an exp per (l, theta).
//
// Both boundaries ride on the same recursion, because the ratio depends on n
// only through n^2 and because
//
//   WignerMaxOrder(l, n) = (-1)^{n+l} WignerMinOrder(l, -n),
//
// so carrying WignerMinOrder(l, +-n) as two running values gives both.
//
// This is more robust than the closed form rather than less. The closed form
// works in logarithms because sqrt((2l)!/...) is of order 4^l and overflows
// long before the value it belongs to, which is bounded by one; each step of
// the recursion multiplies by about 2 s c = sin(theta), so nothing large is
// ever formed. The special values at theta = 0 and pi come out of the seeds
// unaided: the ratio is 0 * infinity there, but the seed is already the exact
// 0 or 1 that the closed form's AtLeft and AtRight branches return, and the
// factor is zero thereafter.
//
// Values are unnormalised. Compute applies sqrt((2l+1)/4pi) to the whole block
// afterwards, which is also the contract a generating supplier must meet.
template <RealFloatingPoint Real>
class BoundaryValues {
 public:
  using Int = std::ptrdiff_t;  ///< Signed index type used throughout the library.

  constexpr BoundaryValues(Int n, const Arguments<Real> &arg)
      : _n{n},
        _l{n < 0 ? -n : n},
        _sinCos{arg.SinHalf() * arg.CosHalf()},
        _atUpperIndex{IntegerPower(n >= 0 ? arg.SinHalf() : arg.CosHalf(),
                                   2 * (n < 0 ? -n : n))},
        _atMinusUpperIndex{IntegerPower(n >= 0 ? arg.CosHalf() : arg.SinHalf(),
                                        2 * (n < 0 ? -n : n))} {}

  // Move to the next degree. Degrees must be visited in ascending order from
  // |n|, which is what Compute's loops already do; the recursion carries no
  // way to skip one or to go back.
  constexpr void Advance() {
    _l++;
    const auto Fl = static_cast<Real>(_l);
    const auto Fn = static_cast<Real>(_n);
    const auto factor =
        std::sqrt(2 * Fl * (2 * Fl - 1) / ((Fl - Fn) * (Fl + Fn))) * _sinCos;
    _atUpperIndex *= factor;
    _atMinusUpperIndex *= factor;
  }

  constexpr auto Degree() const { return _l; }

  // d^l_{n,-l}, which is WignerMinOrder(l, n).
  constexpr auto MinOrder() const { return _atUpperIndex; }

  // d^l_{n,l}, which is WignerMaxOrder(l, n).
  constexpr auto MaxOrder() const {
    return MinusOneToPower<Real>(_n + _l) * _atMinusUpperIndex;
  }

 private:
  Int _n;
  Int _l;
  Real _sinCos;
  Real _atUpperIndex;
  Real _atMinusUpperIndex;
};

// The square-root tables the recursion indexes: sqrt(k) and its reciprocal,
// for k up to lMax + max(mMax, |n|).
//
// Lifted out of Wigner::PreCompute for the same reason as ComputeBlock: a
// generating grid needs them without needing a table, and two definitions of
// the same tables would be one too many. They are the tiny tables that replace
// the large one -- 2 lMax + 1 entries each.
template <RealFloatingPoint Real>
auto PreComputeTables(std::ptrdiff_t lMax, std::ptrdiff_t mMax,
                      std::ptrdiff_t nMax) {
  using Int = std::ptrdiff_t;  ///< Signed index type used throughout the library.
  const auto size = lMax + std::max(mMax, nMax) + 1;
  auto sqrtInt = std::vector<Real>();
  auto sqrtIntInv = std::vector<Real>();
  sqrtInt.reserve(size);
  sqrtIntInv.reserve(size);
  std::generate_n(std::back_inserter(sqrtInt), size, [m = Int{0}]() mutable {
    return std::sqrt(static_cast<Real>(m++));
  });
  std::transform(sqrtInt.begin(), sqrtInt.end(),
                 std::back_inserter(sqrtIntInv),
                 [](auto x) { return x > 0 ? 1 / x : 0; });
  return std::pair(std::move(sqrtInt), std::move(sqrtIntInv));
}

// The recursion itself, as a pure function of a destination view, an upper
// index, a colatitude and the two square-root tables.
//
// Lifted out of Wigner::Compute unchanged, so that the values can be written
// somewhere other than a stored table -- into per-thread scratch inside a
// transform, which is what a generating grid does (core-plan.md step F', T11).
// Wigner::Compute is now the wrapper that points the view at its own storage.
// The destination's degree and order bounds come from the view, so a caller
// wanting only the degrees up to some truncation asks for a view of that
// extent and pays for no more.
template <RealFloatingPoint Real, OrderIndexRange MRange>
constexpr void ComputeBlock(GSHView<Real, MRange> d, std::ptrdiff_t n,
                            Real theta, std::span<const Real> sqrtInt,
                            std::span<const Real> sqrtIntInv) {
  using Int = std::ptrdiff_t;  ///< Signed index type used throughout the library.

  // The extent to fill comes from the view rather than from any table, which
  // is what lets a caller ask for the degrees up to a truncation and pay for
  // no more.
  const auto lMax = d.MaxDegree();
  const auto mBound = d.MaxOrder();

  auto arg = Arguments(theta);
  const auto cos = std::cos(theta);
  const auto nAbs = std::abs(n);

  // Set the values for l == |n|
  //
  // This is the seed row, and at l = |n| the closed form reduces to
  //
  //   WignerMinOrder(l, -m) = sqrt(C(2l, l+m)) s^{l-m} c^{l+m},
  //
  // whose binomial row is generated exactly by the standard step
  // C(2l, k) = C(2l, k-1) (2l - k + 1) / k. The row is at most 2|n| + 1
  // long -- five entries for a rank-2 application -- so unlike the boundary
  // recursion this is not about cost.
  //
  // It is about lgamma. glibc's writes the global signgam, and ComputeAll
  // calls Compute from every thread, so the closed form is a data race here
  // -- benign, since nothing reads signgam, but the only genuine one
  // ThreadSanitizer finds in this library (core-plan.md step F'). Leaving
  // this row on the closed form while the degree loop moved off it would
  // have left the race exactly where it was. The values are also exact this
  // way, where the closed form was merely accurate.
  {
    const auto l = nAbs;
    const auto s = arg.SinHalf();
    const auto c = arg.CosHalf();
    auto m = d[l].MinOrder();
    auto iter = d[l].begin();
    auto finish = d[l].end();

    // C(2l, l+m) at the first order stored, formed by the same step.
    auto binomial = static_cast<Real>(1);
    for (auto k = Int{1}; k <= l + m; k++) {
      binomial *= static_cast<Real>(2 * l - k + 1) / static_cast<Real>(k);
    }

    while (iter != finish) {
      const auto root = std::sqrt(binomial);
      *iter++ = n >= 0 ? root * IntegerPower(s, l - m) *
                             IntegerPower(c, l + m)
                       : MinusOneToPower<Real>(l - m) * root *
                             IntegerPower(s, l + m) *
                             IntegerPower(c, l - m);
      binomial *= static_cast<Real>(l - m) / static_cast<Real>(l + m + 1);
      m++;
    }
  }

  // The boundary terms of every higher degree, on the one-term recursion
  // that replaces the closed form at m = +-l.
  auto boundary = BoundaryValues<Real>(n, arg);

  // Set the values for l == n+1 if needed.
  if (nAbs < lMax) {
    const auto l = nAbs + 1;
    const auto mMin = d[l].MinOrder();
    const auto mMax = d[l].MaxOrder();
    auto m = mMin;

    // The boundary values are read only while the degree is still growing:
    // every use below is guarded by l <= mMax, and that degree's mMax is
    // min(l, mBound). Once l passes mBound they are never wanted again, so
    // the recursion stops rather than being advanced unused.
    if (l <= mBound) boundary.Advance();

    // Set iterators
    auto iterMinusOne = d[l - 1].begin();
    auto finishMinusOne = d[l - 1].end();
    auto iter = d[l].begin();

    // Add in value at m == -l if needed.
    if constexpr (std::same_as<MRange, All>) {
      if (l <= mMax) {
        *iter++ = boundary.MinOrder();
        m++;
      }
    }

    // Add in interior orders using one-term recursion.
    {
      const auto alpha = (2 * l - 1) * l * cos * sqrtIntInv[l + nAbs];
      const auto beta = (n < 0 ? -1 : 1) * (2 * l - 1) * sqrtIntInv[l + nAbs];

      while (iterMinusOne != finishMinusOne) {
        const auto f1 =
            (alpha - beta * m) * sqrtIntInv[l - m] * sqrtIntInv[l + m];
        *iter++ = f1 * *iterMinusOne++;
        m++;
      }
    }

    // Add in value at m == l if needed
    if (l <= mMax) {
      *iter++ = boundary.MaxOrder();
    }
  }

  // Do the remaining degrees
  for (auto l = nAbs + 2; l <= lMax; l++) {
    const auto mMin = d[l].MinOrder();
    const auto mMax = d[l].MaxOrder();
    auto m = mMin;

    if (l <= mBound) boundary.Advance();

    // Set iterators.
    auto iterMinusTwo = d[l - 2].begin();
    auto finishMinusTwo = d[l - 2].end();
    auto iterMinusOne = d[l - 1].begin();
    auto iter = d[l].begin();

    // Add in lower boundary terms if still growing.
    if constexpr (std::same_as<MRange, All>) {
      if (l <= mMax) {
        {
          // Add in the m == -l term.
          *iter++ = boundary.MinOrder();
          m++;
        }
        {
          // Now do the m == -l+1 term using one-point recursion.
          const auto f1 = (2 * l - 1) * (l * (l - 1) * cos - m * n) *
                          sqrtIntInv[l - n] * sqrtIntInv[l + n] *
                          sqrtIntInv[l - m] * sqrtIntInv[l + m] /
                          static_cast<Real>(l - 1);
          *iter++ = f1 * (*iterMinusOne++);
          m++;
        }
      }

      // Add in the lower boundary term at the critical degree.
      if (l == mMax + 1) {
        const auto f1 = (2 * l - 1) * (l * (l - 1) * cos - m * n) *
                        sqrtIntInv[l - n] * sqrtIntInv[l + n] *
                        sqrtIntInv[l - m] * sqrtIntInv[l + m] /
                        static_cast<Real>(l - 1);
        *iter++ = f1 * (*iterMinusOne++);
        m++;
      }
    }

    // Apply two-term recusion for the interior orders.
    {
      const auto alpha =
          (2 * l - 1) * l * cos * sqrtIntInv[l - n] * sqrtIntInv[l + n];
      const auto beta = (2 * l - 1) * n * sqrtIntInv[l - n] *
                        sqrtIntInv[l + n] / static_cast<Real>(l - 1);
      const auto gamma = l * sqrtInt[l - 1 - n] * sqrtInt[l - 1 + n] *
                         sqrtIntInv[l - n] * sqrtIntInv[l + n] /
                         static_cast<Real>(l - 1);

      while (iterMinusTwo != finishMinusTwo) {
        const auto denom = sqrtIntInv[l - m] * sqrtIntInv[l + m];
        const auto f1 = (alpha - beta * m) * denom;
        const auto f2 =
            gamma * sqrtInt[l - 1 - m] * sqrtInt[l - 1 + m] * denom;
        *iter++ = f1 * *iterMinusOne++ - f2 * *iterMinusTwo++;
        m++;
      }
    }

    // Add in the upper boundary terms if still growing.
    if (l <= mMax) {
      // Add in m == l - 1 term using one-point recursion.
      {
        const auto f1 = (2 * l - 1) * (l * (l - 1) * cos - m * n) *
                        sqrtIntInv[l - n] * sqrtIntInv[l + n] *
                        sqrtIntInv[l - m] * sqrtIntInv[l + m] /
                        static_cast<Real>(l - 1);
        *iter++ = f1 * (*iterMinusOne++);
        m++;
      }
      // Now do m == l.
      *iter++ = boundary.MaxOrder();
    }

    // Add in the upper boundary term at the critical degree.
    if (l == mMax + 1) {
      // Update the iterators.

      const auto f1 = (2 * l - 1) * (l * (l - 1) * cos - m * n) *
                      sqrtIntInv[l - n] * sqrtIntInv[l + n] *
                      sqrtIntInv[l - m] * sqrtIntInv[l + m] /
                      static_cast<Real>(l - 1);
      *iter++ = f1 * (*iterMinusOne++);
    }
  }

  // Orthonormalise: the stored value at (l, m) becomes
  // sqrt((2l+1)/(4 pi)) d^l_{nm}. This is the only normalisation the
  // library offers (core-plan step A2).
  {
    const auto factor =
        std::numbers::inv_sqrtpi_v<Real> / static_cast<Real>(2);
    for (auto l : d.Degrees()) {
      auto start = d[l].begin();
      auto finish = d[l].end();
      std::transform(start, finish, start, [l, factor](auto p) {
        return factor * std::sqrt(static_cast<Real>(2 * l + 1)) * p;
      });
    }
  }
}

}  // namespace WignerDetails

/**
 * @brief A table of generalised Legendre functions over a set of colatitudes.
 *
 * @tparam _Real The precision.
 * @tparam _MRange Whether each block holds all orders or only the
 * non-negative ones.
 * @tparam _NRange Which upper indices the table covers.
 * @tparam _AngleRange Whether the table holds one colatitude or many.
 */
template <RealFloatingPoint _Real, OrderIndexRange _MRange = All,
          IndexRange _NRange = Single,
          AngleIndexRange _AngleRange = Single>
class Wigner {
 public:
  using Int = std::ptrdiff_t;  ///< Signed index type used throughout the library.
  using Real = _Real;  ///< The precision.
  using MRange = _MRange;  ///< Whether all orders are stored, or only the non-negative ones.
  using NRange = _NRange;  ///< Which upper indices are covered.
  using AngleRange = _AngleRange;  ///< Whether one colatitude is held, or many.

  /** @brief An empty table. */
  Wigner() = default;

  /**
   * @brief Builds the table over a set of colatitudes.
   * @param lMax The largest degree.
   * @param mMax The largest order; blocks stop widening beyond it.
   * @param nMax The largest upper index.
   * @param theta The colatitudes, in @f$(0, \pi)@f$.
   */
  template <std::ranges::range Range>
  requires RealFloatingPoint<std::ranges::range_value_t<Range>>
  Wigner(Int lMax, Int mMax, Int nMax, Range &&theta)
      : _lMax{lMax}, _mMax{mMax}, _nMax{nMax}, _nTheta(theta.size()) {
    // Compute the offsets and allocate memory.
    {
      _offset.reserve(NumberOfUpperIndices() * NumberOfAngles());
      auto size = std::size_t{0};
      for (auto [n, iTheta] : Indices()) {
        _offset.push_back(size);
        size += GSHIndices<MRange>(MaxDegree(), _mMax, n).Size();
      }
      _data = std::vector<Real>(size);
    }
    ComputeAll(theta);
  }

  /** @brief Builds the table over one colatitude. */
  Wigner(Int lMax, Int mMax, Int nMax, Real theta)
  requires std::same_as<AngleRange, Single>
      : Wigner(lMax, mMax, nMax, std::vector{theta}) {}

  /** @brief Copy constructor. */
  Wigner(const Wigner &) = default;
  /** @brief Move constructor. */
  Wigner(Wigner &&) = default;
  /** @brief Copy assignment. */
  Wigner &operator=(const Wigner &) = default;
  /** @brief Move assignment. */
  Wigner &operator=(Wigner &&) = default;

  /**
   * @brief Recomputes the table at new colatitudes, reusing its storage.
   * @param theta The new colatitudes; there must be as many as before.
   */
  template <std::ranges::range Range>
  requires RealFloatingPoint<std::ranges::range_value_t<Range>>
  void ReCompute(Range &&theta) {
    assert(theta.size() == NumberOfAngles());
    ComputeAll(theta);
  }

  /** @brief Recomputes the table at a new colatitude. */
  void ReCompute(Real theta)
  requires std::same_as<AngleRange, Single>
  {
    ComputeAll(std::vector{theta});
  }

  /** @brief The smallest degree stored at upper index @p n, namely @f$|n|@f$. */
  auto MinDegree(Int n) const {
    assert(std::abs(n) <= _nMax);
    return std::abs(n);
  }
  /** @brief The smallest degree stored. */
  auto MinDegree() const
  requires std::same_as<NRange, Single>
  {
    return std::abs(_nMax);
  }
  /** @brief The largest degree stored. */
  auto MaxDegree() const { return _lMax; }

  /** @brief Every degree stored. */
  auto Degrees() const
  requires std::same_as<NRange, Single>
  {
    return std::ranges::views::iota(MinDegree(), MaxDegree() + 1);
  }

  /** @brief Every degree stored at upper index @p n. */
  auto Degrees(Int n) const {
    return std::ranges::views::iota(MinDegree(n), MaxDegree() + 1);
  }

  /** @brief The smallest order stored at degree @p l. */
  auto MinOrder(Int l) const {
    assert(l >= 0 && l <= MaxDegree());
    if constexpr (std::same_as<MRange, All>) {
      return -std::min(l, _mMax);
    } else {
      return 0;
    }
  }
  auto MaxOrder() const { return _mMax; }
  /** @brief The largest order stored at degree @p l. */
  auto MaxOrder(Int l) const { return std::min(l, _mMax); }

  /** @brief Every order stored at degree @p l. */
  auto Orders(Int l) const {
    return std::ranges::views::iota(MinOrder(l), MaxOrder(l) + 1);
  }

  // Return upper index information.
  /** @brief The smallest upper index stored. */
  auto MinUpperIndex() const {
    if constexpr (std::same_as<_NRange, All>) {
      return -_nMax;
    } else if constexpr (std::same_as<_NRange, NonNegative>) {
      return Int{0};
    } else {
      return _nMax;
    }
  }

  /** @brief The largest upper index stored. */
  auto MaxUpperIndex() const { return _nMax; }

  /** @brief Every upper index stored. */
  auto UpperIndices() const {
    return std::ranges::views::iota(MinUpperIndex(), MaxUpperIndex() + 1);
  }

  /** @brief How many upper indices are stored. */
  auto NumberOfUpperIndices() const {
    return MaxUpperIndex() - MinUpperIndex() + 1;
  }

  // Return angle information.
  /** @brief How many colatitudes are stored. */
  auto NumberOfAngles() const { return _nTheta; }

  /** @brief Indices of the stored colatitudes. */
  auto AngleIndices() const {
    return std::ranges::views::iota(Int{0}, _nTheta);
  }

  /**
   * @brief Every @f$(n, i_\theta)@f$ pair, in storage order.
   * @details Upper index outermost, colatitude fastest, which is how the
   * blocks are laid out.
   */
  auto Indices() const {
    return std::ranges::views::cartesian_product(UpperIndices(),
                                                 AngleIndices());
  }

  /** @brief The block of values for upper index @p n at colatitude @p iTheta. */
  auto operator[](Int n, Int iTheta) const {
    return ConstGSHView<Real, MRange>(MaxDegree(), MaxOrder(), n,
                                      &_data[Offset(n, iTheta)]);
  }

  /** @brief The block for upper index @p n, when only one colatitude is held. */
  auto operator[](Int n) const
  requires std::same_as<AngleRange, Single> && (!std::same_as<NRange, Single>)
  {
    return operator[](n, 0);
  }

  /** @brief The block at colatitude @p iTheta, when only one upper index is held. */
  auto operator[](Int iTheta) const
  requires std::same_as<NRange, Single> && (!std::same_as<AngleRange, Single>)
  {
    return operator[](_nMax, iTheta);
  }

  /** @brief The row of orders at degree @p l, when one block is held. */
  auto operator[](Int l) const
  requires std::same_as<NRange, Single> && std::same_as<AngleRange, Single>
  {
    return operator[](_nMax, 0)[l];
  }

 private:
  Int _lMax;    // Maximum degree.
  Int _mMax;    // Maximum order.
  Int _nMax;    // Maximum upper index.
  Int _nTheta;  // Number of colatitudes.

  // Vector storing the values.
  std::vector<Real> _data;

  // Vector storing data offsets.
  std::vector<std::size_t> _offset;

  // Offset for values for (n, iTheta).
  auto Offset(Int n, Int iTheta) const {
    return _offset[NumberOfAngles() * (n - MinUpperIndex()) + iTheta];
  }

  template <std::ranges::range Range>
  requires RealFloatingPoint<std::ranges::range_value_t<Range>>
  void ComputeAll(Range &&thetaRange) {
    const auto [sqrtInt, sqrtIntInv] = WignerDetails::PreComputeTables<Real>(
        MaxDegree(), MaxOrder(), MaxUpperIndex());
    const auto sqrtIntView = std::span<const Real>(sqrtInt);
    const auto sqrtIntInvView = std::span<const Real>(sqrtIntInv);

    // Flattened to an integer loop and decoded inside. OpenMP's canonical loop
    // form wants an integer induction variable or, from 5.0, a random-access
    // iterator loop; a structured binding over a cartesian_product view is
    // neither obviously conforming nor portable (core-plan.md F8).
    //
    // The region is suppressed when one is already open, so that a caller
    // threading over grids or slices does not nest with this one. Exactly one
    // level threads.
    const auto nAngles = NumberOfAngles();
    const auto count = NumberOfUpperIndices() * nAngles;
    const auto minUpperIndex = MinUpperIndex();
    const bool nested = omp_in_parallel();

#pragma omp parallel for schedule(static) if (!nested)
    for (Int index = 0; index < count; index++) {
      const auto n = minUpperIndex + index / nAngles;
      const auto iTheta = index % nAngles;
      Compute(n, iTheta, thetaRange[iTheta], sqrtIntView, sqrtIntInvView);
    }
  }

  // Point the recursion at this table's storage for one (n, iTheta).
  constexpr void Compute(Int n, Int iTheta, Real theta,
                         std::span<const Real> sqrtInt,
                         std::span<const Real> sqrtIntInv) {
    WignerDetails::ComputeBlock(
        GSHView<Real, MRange>(_lMax, _mMax, n, &_data[Offset(n, iTheta)]), n,
        theta, sqrtInt, sqrtIntInv);
  }

};
}  // namespace GSHTrans

#endif
