// 22 -- Wigner 3-j symbols, and the check that says when to trust them
//
// What this shows. The 3-j symbols
//
//     ( l1 l2 l3 )
//     ( m1 m2 m3 )
//
// are the coupling coefficients of three angular momenta. A spherical-harmonic
// code wants them for Gaunt integrals -- the integral of a product of three
// harmonics is a product of two 3-j symbols -- and for mode coupling in
// normal-mode seismology. A symbol is non-zero only if m1 + m2 + m3 = 0,
// |mi| <= li, and the degrees satisfy the triangle rule
// |l1 - l3| <= l2 <= l1 + l3. They touch no grid, transform or field, so this
// example includes only GSHTrans/Core.hpp.
//
// The library offers three shapes:
//
//   Wigner3jSymbol(l1,l2,l3, m1,m2,m3)  one symbol, for convenience
//   Wigner3jMatrix(l1,l2,l3)            the whole (m1, m3) plane at fixed
//                                       degrees, with m2 fixed by the rule
//   Wigner3jStack(l1,l3)                one such matrix per middle degree l2
//
// The table is the primitive: a symbol on its own costs a whole table, so ask
// for the table if you want more than one.
//
// **The important thing in this example is the last section.** The values are
// generated by the Schulten-Gordon algorithm. At fixed m1, the symbols as a
// function of m2 satisfy a three-term recurrence with a growing and a
// decaying solution. Each row of the table is built inward from both ends of
// its range -- the stable direction -- matched where the two halves overlap,
// and normalised from the unitary property (2 l1 + 1) sum_{m2} g(m2)^2 = 1.
// That matters because a one-directional recursion loses these values
// exponentially near *stretched* triangles -- where one degree approaches the
// sum of the other two, which is the top of every coupling sum rather than an
// exotic corner. docs/gshtrans-reference.tex, "The 3-j symbols", has more.
//
// Every row is checked against the recurrence that defines it before it is
// handed back; a row that fails throws std::runtime_error, so a table that has
// gone wrong is refused rather than returned.
//
// Read first. Nothing: this example is independent of the rest of the series.
//
// The output. A table's size and one symbol by three routes; zeros outside
// the selection rules; two closed forms; a stack's l2 range; the
// completeness sum; a stretched symbol at higher degree; and the
// cyclic-permutation check at (100, 100, 150).
//

#include <GSHTrans/Core.hpp>
#include <cmath>
#include <iomanip>
#include <iostream>
#include <stdexcept>

int main() {
  using namespace GSHTrans;

  std::cout << std::scientific << std::setprecision(3);

  //------------------------------------------------------------------------//
  //                        A table, and what is in it                       //
  //------------------------------------------------------------------------//

  // The (m1, m3) plane for degrees (3, 4, 5): 7 x 11 values, row-major with
  // m1 slowest. Entries whose implied |m2| exceeds l2 are stored as zero.
  // table(m1, m2, m3) takes all three orders; table(m1, m3) implies m2.
  const auto table = Wigner3jMatrix<double>(3, 4, 5);
  std::cout << "A table for degrees (3, 4, 5) holds " << table.size()
            << " values,\n"
            << "over m1 in [-3, 3] and m3 in [-5, 5], with m2 = -(m1 + m3).\n";

  std::cout << "\n  (3 4 5; 1 -3 2) = " << table(1, -3, 2) << "\n"
            << "  the same, by (m1, m3) = " << table(1, 2) << "\n"
            << "  and the free function = "
            << Wigner3jSymbol<double>(3, 4, 5, 1, -3, 2) << "\n";

  // Queries that break a selection rule are zero rather than an error: that
  // is the mathematically consistent value, and it keeps a coupling sum from
  // needing a guard at every term.
  std::cout << "\nOutside the selection rules the symbol is zero, not an "
               "error:\n"
            << "  orders not summing to zero = " << table(1, 1, 1) << "\n"
            << "  an order beyond its degree = " << table(7, 0) << "\n";

  //------------------------------------------------------------------------//
  //                       Two closed forms, as a check                      //
  //------------------------------------------------------------------------//

  // (j j 0; m -m 0) = (-1)^{j-m} / sqrt(2j+1), reproduced to rounding.
  // M1Axis() iterates m1 over [-l1, l1].
  {
    constexpr auto j = 7;
    const auto zeroDegree = Wigner3jMatrix<double>(j, j, 0);
    auto worst = 0.0;
    for (auto m : zeroDegree.M1Axis()) {
      const auto want =
          ((j - m) % 2 == 0 ? 1.0 : -1.0) / std::sqrt(2.0 * j + 1);
      worst = std::max(worst, std::abs(zeroDegree(m, 0) - want));
    }
    std::cout << "\n(j j 0; m -m 0) against its closed form, j = " << j << ": "
              << worst << "\n";
    if (!(worst < 1e-14)) return 1;
  }

  // The fully stretched symbol, where every factorial cancels:
  //   (l1 l2 l1+l2; l1 l2 -(l1+l2)) = 1 / sqrt(2 l3 + 1)
  {
    constexpr auto l1 = 5;
    constexpr auto l2 = 8;
    constexpr auto l3 = l1 + l2;
    const auto stretched = Wigner3jMatrix<double>(l1, l2, l3);
    const auto want = 1 / std::sqrt(2.0 * l3 + 1);
    const auto error = std::abs(stretched(l1, l2, -l3) - want);
    std::cout << "the fully stretched symbol against 1/sqrt(2 l3 + 1): "
              << error << "\n";
    if (!(error < 1e-14)) return 1;
  }

  //------------------------------------------------------------------------//
  //                    A stack, over the middle degree                      //
  //------------------------------------------------------------------------//

  // Wigner3jStack(l1, l3) holds one Wigner3jMatrix for each middle degree
  // l2, by default over the triangle range |l1 - l3| <= l2 <= l1 + l3; the
  // middle degree is the one a coupling sum usually runs over.
  {
    const auto stack = Wigner3jStack<double>(4, 6);
    std::cout << "\nA stack for (l1, l3) = (4, 6) covers l2 in ["
              << stack.L2Axis().Min() << ", " << stack.L2Axis().Max()
              << "],\nwhich is the triangle range, as " << stack.size()
              << " tables.\n";
  }

  //------------------------------------------------------------------------//
  //          Completeness, the stretched corner, and a real check          //
  //------------------------------------------------------------------------//

  // Summing the squares over the whole plane gives one, to rounding, for any
  // triple satisfying the triangle rule: each row is normalised to
  // 1/(2 l1 + 1) and there are 2 l1 + 1 rows. Because the algorithm
  // normalises by this identity, it holds by construction and says little
  // about whether the values are right; the last check below is the one that
  // does.
  {
    auto sum = 0.0;
    for (auto value : table) sum += value * value;
    std::cout << "\nThe completeness relation on (3, 4, 5): sum of squares = "
              << sum << ", departure from one = " << std::abs(sum - 1) << "\n";
  }

  // Stretched triangles at high degree are the case a one-directional
  // recursion cannot do: the error grows exponentially along the row, and
  // the result is still finite and in a correctly shaped table, so nothing
  // looks wrong. Recursing inward from both ends and matching gives the
  // closed-form value 1/sqrt(2 l3 + 1) to rounding.
  {
    const auto stretched = Wigner3jMatrix<double>(40, 40, 80);
    const auto want = 1 / std::sqrt(2.0 * 80 + 1);
    std::cout << "\n(40, 40, 80) at the stretched corner, against "
                 "1/sqrt(2 l3 + 1): "
              << std::abs(stretched(40, 40, -80) - want) << "\n";
    if (!(std::abs(stretched(40, 40, -80) - want) < 1e-14)) return 1;
  }

  // The check that the values really are right is not the completeness
  // relation -- each row is normalised by it, so it holds by construction --
  // but the symmetry of the symbols under a cyclic permutation of their
  // columns:
  //
  //     (l1 l2 l3; m1 m2 m3) = (l2 l3 l1; m2 m3 m1).
  //
  // Table b is the permuted one, so its (first, third) orders are (m2, m1).
  // Computing it runs the recursion along entirely different lines, so
  // agreement is independent evidence. The recurrence check inside the
  // library cannot replace it: the recurrence is homogeneous, so it cannot
  // see an overall scale or sign on a row.
  {
    constexpr auto l1 = 100, l2 = 100, l3 = 150;
    const auto a = Wigner3jMatrix<double>(l1, l2, l3);
    const auto b = Wigner3jMatrix<double>(l2, l3, l1);
    auto worst = 0.0;
    for (auto m1 : a.M1Axis())
      for (auto m3 : a.M3Axis()) {
        const auto m2 = -(m1 + m3);
        if (std::abs(m2) > l2) continue;
        worst = std::max(worst, std::abs(b(m2, m1) - a(m1, m3)));
      }
    std::cout << "(100, 100, 150) against its cyclic permutation, which is an "
                 "independent\nroute to the same numbers: "
              << worst << "\n";
    if (!(worst < 1e-13)) return 1;
  }

  std::cout << "\nThe working range is the whole triangle space, so far as it "
               "has been\nmeasured: agreement to 1e-16 at (200, 200, 200) and "
               "1e-15 at\n(1000, 1000, 1999). Where a table cannot be trusted "
               "it is refused, not\nreturned.\n";

  return 0;
}
