// 22 -- Wigner 3-j symbols, and the check that says when to trust them
//
// The 3-j symbols are the coupling coefficients of three angular momenta, and
// what a spherical-harmonic library wants them for is Gaunt integrals and
// mode coupling. The library offers three shapes:
//
//   Wigner3jSymbol(l1,l2,l3, m1,m2,m3)  one symbol, for convenience
//   Wigner3jMatrix(l1,l2,l3)            the whole (m1, m3) plane at fixed
//                                       degrees, with m2 fixed by the rule
//   Wigner3jStack(l1,l3)                one such matrix per middle degree l2
//
// The table is the primitive: a symbol on its own costs a whole table, so ask
// for the table if you want more than one.
//
// **The important thing in this example is the last section.** The values are
// generated by the Schulten-Gordon algorithm: each row of the table is built
// inward from both ends of its range, matched in the middle, and normalised
// from the unitary property of the symbols. That matters because a
// one-directional recursion loses these values exponentially near *stretched*
// triangles -- where one degree approaches the sum of the other two, which is
// the top of every coupling sum rather than an exotic corner.
//
// Every row is checked against the recurrence that defines it before it is
// handed back, so a table that has gone wrong is refused rather than returned.
//

#include <GSHTrans/Core>
#include <cmath>
#include <iomanip>
#include <iostream>
#include <stdexcept>

int main() {
  using namespace GSHTrans;

  std::cout << std::scientific << std::setprecision(3);

  //------------------------------------------------------------------------//
  //                        A table, and what is in it                       //
  //------------------------------------------------------------------------//

  const auto table = Wigner3jMatrix<double>(3, 4, 5);
  std::cout << "A table for degrees (3, 4, 5) holds " << table.size()
            << " values,\n"
            << "over m1 in [-3, 3] and m3 in [-5, 5], with m2 = -(m1 + m3).\n";

  std::cout << "\n  (3 4 5; 1 -3 2) = " << table(1, -3, 2) << "\n"
            << "  the same, by (m1, m3) = " << table(1, 2) << "\n"
            << "  and the free function = "
            << Wigner3jSymbol<double>(3, 4, 5, 1, -3, 2) << "\n";

  // Queries that break a selection rule are zero rather than an error: that
  // is the mathematically consistent value, and it keeps a coupling sum from
  // needing a guard at every term.
  std::cout << "\nOutside the selection rules the symbol is zero, not an "
               "error:\n"
            << "  orders not summing to zero = " << table(1, 1, 1) << "\n"
            << "  an order beyond its degree = " << table(7, 0) << "\n";

  //------------------------------------------------------------------------//
  //                       Two closed forms, as a check                      //
  //------------------------------------------------------------------------//

  // (j j 0; m -m 0) = (-1)^{j-m} / sqrt(2j+1), which the library reproduces
  // exactly.
  {
    constexpr auto j = 7;
    const auto zeroDegree = Wigner3jMatrix<double>(j, j, 0);
    auto worst = 0.0;
    for (auto m : zeroDegree.M1Axis()) {
      const auto want =
          ((j - m) % 2 == 0 ? 1.0 : -1.0) / std::sqrt(2.0 * j + 1);
      worst = std::max(worst, std::abs(zeroDegree(m, 0) - want));
    }
    std::cout << "\n(j j 0; m -m 0) against its closed form, j = " << j << ": "
              << worst << "\n";
    if (!(worst < 1e-14)) return 1;
  }

  // The fully stretched symbol, where every factorial cancels:
  //   (l1 l2 l1+l2; l1 l2 -(l1+l2)) = 1 / sqrt(2 l3 + 1)
  {
    constexpr auto l1 = 5;
    constexpr auto l2 = 8;
    constexpr auto l3 = l1 + l2;
    const auto stretched = Wigner3jMatrix<double>(l1, l2, l3);
    const auto want = 1 / std::sqrt(2.0 * l3 + 1);
    const auto error = std::abs(stretched(l1, l2, -l3) - want);
    std::cout << "the fully stretched symbol against 1/sqrt(2 l3 + 1): "
              << error << "\n";
    if (!(error < 1e-14)) return 1;
  }

  //------------------------------------------------------------------------//
  //                    A stack, over the middle degree                      //
  //------------------------------------------------------------------------//

  {
    const auto stack = Wigner3jStack<double>(4, 6);
    std::cout << "\nA stack for (l1, l3) = (4, 6) covers l2 in ["
              << stack.L2Axis().Min() << ", " << stack.L2Axis().Max()
              << "],\nwhich is the triangle range, as " << stack.size()
              << " tables.\n";
  }

  //------------------------------------------------------------------------//
  //             The completeness relation, and the refusal                  //
  //------------------------------------------------------------------------//

  // Summing the squares over the whole plane gives one, exactly, for any
  // triple satisfying the triangle rule. It needs no reference to compare
  // against, which is what lets the library check itself.
  {
    auto sum = 0.0;
    for (auto value : table) sum += value * value;
    std::cout << "\nThe completeness relation on (3, 4, 5): sum of squares = "
              << sum << ", departure from one = " << std::abs(sum - 1) << "\n";
  }

  // Stretched triangles at high degree are the case a one-directional
  // recursion cannot do: it would return numbers of order 1e9 here, finite
  // and in a correctly shaped table. Recursing inward from both ends and
  // matching gives the exact answer instead.
  {
    const auto stretched = Wigner3jMatrix<double>(40, 40, 80);
    const auto want = 1 / std::sqrt(2.0 * 80 + 1);
    std::cout << "\n(40, 40, 80) at the stretched corner, against "
                 "1/sqrt(2 l3 + 1): "
              << std::abs(stretched(40, 40, -80) - want) << "\n";
    if (!(std::abs(stretched(40, 40, -80) - want) < 1e-14)) return 1;
  }

  // The check that the values really are right is not the completeness
  // relation -- each row is normalised by it, so it holds by construction --
  // but the symmetry of the symbols under a cyclic permutation of their
  // columns. That runs the recursion along entirely different lines.
  {
    constexpr auto l1 = 100, l2 = 100, l3 = 150;
    const auto a = Wigner3jMatrix<double>(l1, l2, l3);
    const auto b = Wigner3jMatrix<double>(l2, l3, l1);
    auto worst = 0.0;
    for (auto m1 : a.M1Axis())
      for (auto m3 : a.M3Axis()) {
        const auto m2 = -(m1 + m3);
        if (std::abs(m2) > l2) continue;
        worst = std::max(worst, std::abs(b(m2, m1) - a(m1, m3)));
      }
    std::cout << "(100, 100, 150) against its cyclic permutation, which is an "
                 "independent\nroute to the same numbers: "
              << worst << "\n";
    if (!(worst < 1e-13)) return 1;
  }

  std::cout << "\nThe working range is the whole triangle space, so far as it "
               "has been\nmeasured: agreement to 1e-16 at (200, 200, 200) and "
               "1e-15 at\n(1000, 1000, 1999). Where a table cannot be trusted "
               "it is refused, not\nreturned.\n";

  return 0;
}
